const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'nike',
      rating: 4.5,
      reviews: 8,
      stock: 20,
      desc: 'A Free Shirt',
    },
    {
      name: 'Free Shirt2',
      slug: 'free-shirt2',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 72,
      brand: 'Nike',
      rating: 4.1,
      reviews: 6,
      stock: 20,
      desc: 'A Free Shirt2',
    },
    {
      name: 'Free Shirt3',
      slug: 'free-shirt3',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Addidas',
      rating: 4.1,
      reviews: 18,
      stock: 10,
      desc: 'A Free Shirt3',
    },
    {
      name: 'Free Shirt4',
      slug: 'free-shirt4',
      category: 'Shirts',
      image: '/images/shirt4.jpg',
      price: 75,
      brand: 'Nike',
      rating: 3.5,
      reviews: 2,
      stock: 15,
      desc: 'A Free Shirt',
    },
    {
      name: 'Free Shirt5',
      slug: 'free-shirt5',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 72,
      brand: 'Nike',
      rating: 4.1,
      reviews: 6,
      stock: 20,
      desc: 'A Free Shirt5',
    },
    {
      name: 'Free Shirt6',
      slug: 'free-shirt6',
      category: 'Shirts',
      image: '/images/shirt4.jpg',
      price: 75,
      brand: 'Nike',
      rating: 3.5,
      reviews: 2,
      stock: 15,
      desc: 'A Free Shirt6',
    },
  ],
};

export default data;
